### ISSUE TITLE
Tests coverage

### ISSUE THREAD

**Issue by f3l1x** [Markette/GopayApi#1]
Highest coverage as we can do.

**Comment by f3l1x** [comment]
Could you please help me with it? :smiley: @hranicka @haltuf

**Comment by haltuf** [comment]
I wonder - does it make sense to create tests for something that is created and managed by someone else (i.e. gopay itself, in this case)?

I'm not even sure, if it is possible: you will have to mock \SoapClient object to reach satisfactory tests coverage. @f3l1x

**Comment by f3l1x** [comment]
I see 2 cons on it.

1) We will see BC breaks and new stuff.

2) Basic coverage could helps with 100% understanding and usage of API.

**Comment by haltuf** [comment]
Alright. Any idea how to mock \SoapClient without having to touch the inner structure of the classes?

**Comment by hranicka** [comment]
I think the only way how to do it right is refactor classes first.

* There is static code usage (usage of GopayConfig, GopayHelper) - we should use mocks of these classes.
* Echo? https://github.com/Markette/GopayApi/blob/master/src/GopayHTTP.php#L49
* \SoapClient

In my opinion, deeper refactoring for Unit tests will be necessary.

The code looks old (originally - "var" properties: https://github.com/Markette/GopayApi/commit/8ac44f1efa8df7270207d281e86a5492e0e6edb9#diff-ddaeb08b83402a1d4c9f4cd1bf65aaf2L9).

**Comment by haltuf** [comment]
This is what I was worried about.. If we refactor official API, then every upcoming update will require more and more changes (in fact, they may diverge in time) - this is the reason why I initially dismissed the idea to write tests for this part when it used to be included in Markette\Gopay.

The question is: does the increased complexity/work connected with unit tests & neccessary refactoring be outweighed by the benefits of this approach? I'm rather sceptical about it (on the other hand, I do not want to sound like a grouch)

**Comment by vojtech-dobes** [comment]
If you want to refactor original classes made by Gopay themselves, I would rather contact them first. @haltuf has very good point.

**Comment by f3l1x** [comment]
Ahmm, I have concidered once again and you're right. I'll keep current tests.

So, we can tag version v2.5 and use it in gopay:master. Right?

**Comment by hranicka** [comment]
Current GopayApi should be OK for gopay:master .

But we should inspect the code (IDE helps) if everything is really OK (eg. called methods exist etc).

**Comment by f3l1x** [comment]
It's time for a new release, we could push it to master for now.

Did you find any IDE errors or warnings? @hranicka

**Comment by hranicka** [comment]
@f3l1x I can check it today evening. I do it on new branch of https://github.com/Markette/Gopay and make pull request to master if everything will be OK? Than you can release new version.

**Comment by f3l1x** [comment]
@hranicka :+1:

**Comment by hranicka** [comment]
Everything seems OK.

I've released GopayApi v2.5.0.

Closing this issue?

**Comment by f3l1x** [comment]
Sure. Great.
